# Generated by Django 2.2.1 on 2019-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Please enter the name of the ent being held at your event', max_length=20)),
                ('description', models.TextField()),
            ],
        ),
    ]
